<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '',
    'Args' => 'Argumente',
    'Audit' => '',
    'Audit Error in Audit Entry #{entry_id}' => 'Audit Fehler in Audit Eintrag #{entry_id}',
    'Audit Module' => 'Audit Modul',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => 'Aufgerufen',
    'Created' => 'Erstellt',
    'Data' => 'Daten',
    'Database Trails' => 'Datenbank Änderungen',
    'Diff' => 'Differenz',
    'Download' => '',
    'Download eml file' => 'Download eml Datei',
    'Duration' => 'Dauer',
    'Email Messages' => 'Emails',
    'Emailed' => 'Gesendet',
    'Entries' => 'Einträge',
    'Entry #{id}' => 'Eintrag #{id}',
    'Entry ID' => 'Eintrag ID',
    'Error' => 'Fehler',
    'Error #{id}' => 'Fehler #{id}',
    'Error Code' => 'Fehler Code',
    'Errors' => 'Fehler',
    'Extra' => '',
    'Extra Data' => 'Extra Daten',
    'File' => 'Datei',
    'From' => 'Von',
    'HTML' => '',
    'HTML Body' => '',
    'Hash' => '',
    'ID' => '',
    'IP' => '',
    'Javascript' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => 'Zeile',
    'Mail' => 'Email',
    'Mail #{id}' => 'Email #{id}',
    'Mails' => 'Emails',
    'Memory' => 'Speicher',
    'Message' => 'Nachricht',
    'Model ID' => 'Model ID',
    'No' => 'Nein',
    'Origin' => 'Quelle',
    'Profiling' => '',
    'Reply' => 'Antworten',
    'Request Method' => 'Anfrage-Methode',
    'Stack Trace' => '',
    'Subject' => 'Betreff',
    'Successful' => 'Erfolgreich',
    'Text' => '',
    'Text Body' => '',
    'To' => 'Zu',
    'Trace' => '',
    'Trail' => 'Änderung',
    'Trail #{id}' => 'Änderung #{id}',
    'Trails' => 'Änderungen',
    'Type' => 'Typ',
    'Yes' => 'Ja',
    'view audit entry' => 'Audit Eintrag ansehen',
    '{message}' => '',
    'Action' => 'Aktion',
    'Difference' => 'Unterschied',
    'Field' => 'Feld',
    'Guest' => 'Gast',
    'New Value' => 'Neuer Wert',
    'Old Value' => 'Alter Wert',
    'Request' => 'Anfrage',
    'User' => 'Benuter',
    'User ID' => 'Benutzer ID',
];
