<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => 'Actie',
    'Added at' => 'Toegevoegd op',
    'Audit Entries' => '',
    'Audit Entry #{entry}' => '',
    'Audit Entry #{id}' => '',
    'Audit Trail' => '',
    'Audit Trail #{id}' => '',
    'Difference' => 'Verschil',
    'End Time' => 'Eindtijd',
    'Entry #{i}' => '',
    'Entry ID' => '',
    'Entry Id' => '',
    'Error #{i}' => 'Fout #{i}',
    'Errors ({i})' => 'Fouten ({i})',
    'Extra data ({i})' => '',
    'Field' => 'Veld',
    'Guest' => 'Gast',
    'ID' => '',
    'Javascript ({i})' => '',
    'Location' => 'Locatie',
    'Max. Memory Usage' => 'Max. Geheugengebruik',
    'Memory Usage' => 'Geheugengebruik',
    'New Value' => 'Nieuwe Waarde',
    'Old Value' => 'Oude Waarde',
    'Request' => 'Verzoek',
    'Request Duration' => 'Verzoeksduur',
    'Request method' => 'Verzoekmethode',
    'Stamp' => 'Tijdstip',
    'Start Time' => 'Starttijd',
    'Trail ({i})' => '',
    'Type' => '',
    'User' => 'Gebruiker',
    'User ID' => 'Gebruiker ID',
];
