<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '',
    'Added' => 'Toegevoegd',
    'Args' => 'Argumenten',
    'Audit' => '',
    'Audit Error in Audit Entry #{entry_id}' => '',
    'Audit Module' => '',
    'Called' => '',
    'Created' => 'Aangemaakt',
    'Data' => '',
    'Database Trails' => '',
    'Diff' => 'Verschil',
    'Duration' => 'Lengte',
    'Email Messages' => 'Emails',
    'Entries' => '',
    'Entry #{id}' => '',
    'Entry ID' => '',
    'Error' => 'Fout',
    'Error #{id}' => 'Fout #{id}',
    'Errors' => 'Fouten',
    'Extra' => '',
    'Extra Data' => '',
    'ID' => '',
    'IP' => '',
    'JS' => '',
    'JS #{id}' => '',
    'Javascript' => '',
    'Memory' => 'Geheugen',
    'No' => 'Neen',
    'Profiling' => '',
    'Request Method' => '',
    'Stack Trace' => '',
    'Trail' => '',
    'Trail #{id}' => '',
    'Trails' => '',
    'Type' => '',
    'Yes' => 'Ja',
    'view audit entry' => 'toon audit entry',
    '{message}' => '',
    'Action' => 'Actie',
    'Difference' => 'Verschil',
    'Field' => 'Veld',
    'Guest' => 'Gast',
    'New Value' => 'Nieuwe Waarde',
    'Old Value' => 'Oude Waarde',
    'Request' => 'Verzoek',
    'User' => 'Gebruiker',
    'User ID' => 'Gebruiker ID',
];
