<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '',
    'Args' => '',
    'Audit' => '',
    'Audit Error in Audit Entry #{entry_id}' => '',
    'Audit Module' => '',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => '',
    'Created' => 'Aangemaakt',
    'Data' => '',
    'Database Trails' => '',
    'Diff' => '',
    'Download' => '',
    'Download eml file' => '',
    'Duration' => 'Duurtijd',
    'Email Messages' => 'Emails',
    'Emailed' => 'Geëmailed',
    'Entries' => '',
    'Entry #{id}' => '',
    'Entry ID' => '',
    'Error' => 'Fout',
    'Error #{id}' => 'Fout #{id}',
    'Error Code' => 'Fout Code',
    'Errors' => 'Fouten',
    'Extra' => '',
    'Extra Data' => '',
    'File' => 'Bestand',
    'From' => 'Van',
    'HTML' => '',
    'HTML Body' => '',
    'Hash' => '',
    'ID' => '',
    'IP' => '',
    'Javascript' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => '',
    'Mail' => 'Email',
    'Mail #{id}' => 'Email #{id}',
    'Mails' => 'Emails',
    'Memory' => 'Geheugen',
    'Message' => 'Bericht',
    'Model ID' => 'Model ID',
    'No' => 'Neen',
    'Origin' => 'Afkomst',
    'Profiling' => '',
    'Reply' => 'Reageren',
    'Request Method' => '',
    'Stack Trace' => '',
    'Subject' => 'Onderwerp',
    'Successful' => 'Gelukt',
    'Text' => 'Tekst',
    'Text Body' => '',
    'To' => 'Naar',
    'Trace' => '',
    'Trail' => '',
    'Trail #{id}' => '',
    'Trails' => '',
    'Type' => '',
    'Yes' => 'Ja',
    'view audit entry' => '',
    '{message}' => '',
    'Action' => 'Actie',
    'Difference' => 'Verschil',
    'Field' => 'Veld',
    'Guest' => 'Gast',
    'New Value' => 'Nieuwe Waarde',
    'Old Value' => 'Oude Waarde',
    'Request' => 'Verzoek',
    'User' => 'Gebruiker',
    'User ID' => 'Gebruiker ID',
];
