<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '<b>{message}</b><br />в <i>{file}</i> на линии <i>{line}</i>.<br/>-- {link}',
    'Action' => 'Действие',
    'Args' => 'Аргументы',
    'Audit' => 'Аудит',
    'Audit Error in Audit Entry #{entry_id}' => 'Аудит ошибка в записи аудита #{entry_id}',
    'Audit Module' => 'Аудит Модуль',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => 'Вызвано',
    'Created' => 'Создано',
    'Data' => 'Данные',
    'Database Trails' => '',
    'Diff' => 'Разница',
    'Difference' => 'Разница',
    'Download' => 'Загрузить',
    'Download eml file' => 'Загрузить eml файл',
    'Duration' => 'Продолжительность',
    'Email Messages' => 'Email сообщение',
    'Emailed' => 'По электронной почте',
    'Entries' => 'Записи',
    'Entry #{id}' => 'Запись #{id}',
    'Entry ID' => 'ID записи',
    'Error' => 'Ошибка',
    'Error #{id}' => 'Ошибка #{id}',
    'Error Code' => 'Код ошибки',
    'Errors' => 'Ошибки',
    'Extra' => 'Дополнительный',
    'Extra Data' => 'Дополнительные данные',
    'Field' => 'Поле',
    'File' => 'Файл',
    'From' => 'От кого',
    'Guest' => 'Гость',
    'HTML' => '',
    'HTML Body' => '',
    'Hash' => 'Хэш',
    'ID' => '',
    'IP' => '',
    'Javascript' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => 'Линия',
    'Mail' => 'Письмо',
    'Mail #{id}' => 'Письмо #{id}',
    'Mails' => 'Письма',
    'Memory' => 'Память',
    'Message' => 'Сообщение',
    'Model ID' => 'ID модели',
    'New Value' => 'Новое значение',
    'No' => 'Нет',
    'Old Value' => 'Старое значение',
    'Origin' => 'Источник',
    'Profiling' => '',
    'Reply' => 'Ответ',
    'Request' => 'Запрос',
    'Request Method' => 'Метод запроса',
    'Stack Trace' => '',
    'Subject' => 'Заголовок',
    'Successful' => 'Успешный',
    'Text' => 'Текст',
    'Text Body' => 'Текст тела',
    'To' => 'Кому',
    'Trace' => '',
    'Trail' => '',
    'Trail #{id}' => '',
    'Trails' => '',
    'Type' => 'Тип',
    'User' => 'Пользователь',
    'User ID' => 'ID пользователя',
    'Yes' => 'Да',
    'view audit entry' => 'вид записи аудита',
    '{message}' => '',
];
