<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '<b>{message}</b><br />v <i>{file}</i> na riadku <i>{line}</i>.<br/>-- {link}',
    'Action' => 'Akcia',
    'Args' => 'Argumenty',
    'Audit' => 'Audit',
    'Audit Error in Audit Entry #{entry_id}' => 'Chyba v položke auditu #{entry_id}',
    'Audit Module' => 'Audit modul',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => 'Volané',
    'Created' => 'Vytvorené',
    'Data' => 'Dáta',
    'Database Trails' => 'Stopa Databázy',
    'Diff' => 'Rozdiel',
    'Difference' => 'Rozdiel',
    'Download' => 'Stiahnuť',
    'Download eml file' => 'Stiahnuť eml súbor',
    'Duration' => 'Trvanie',
    'Email Messages' => 'Email správy',
    'Emailed' => 'Odoslané emailom',
    'Entries' => 'Záznamy',
    'Entry #{id}' => 'Záznam #{id}',
    'Entry ID' => 'ID záznamu',
    'Error' => 'Chyba',
    'Error #{id}' => 'Chyba #{id}',
    'Error Code' => 'Kód chyby',
    'Errors' => 'Chyby',
    'Extra' => 'Extra',
    'Extra Data' => 'Extra dáta',
    'Field' => 'Pole',
    'File' => 'Súbor',
    'From' => 'OD',
    'Guest' => 'Hosť',
    'HTML' => '',
    'HTML Body' => 'Telo HTML',
    'Hash' => '',
    'ID' => '',
    'IP' => '',
    'Javascript' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => 'Riadok',
    'Mail' => 'Email',
    'Mail #{id}' => 'Email #{id}',
    'Mails' => 'Maily',
    'Memory' => 'Pamäť',
    'Message' => 'Správa',
    'Model ID' => 'ID modelu',
    'New Value' => 'Nová hodnota',
    'No' => 'Nie',
    'Old Value' => 'Stará hodnota',
    'Origin' => 'Pôvod',
    'Profiling' => 'Profilovanie',
    'Reply' => 'Odpoveď',
    'Request' => 'Požiadavok',
    'Request Method' => 'Metóda požiadavku',
    'Stack Trace' => '',
    'Subject' => 'Predmet',
    'Successful' => 'Úspešný',
    'Text' => '',
    'Text Body' => 'Textové telo',
    'To' => 'Komu',
    'Trace' => '',
    'Trail' => 'Stopa',
    'Trail #{id}' => 'Stopa #{id}',
    'Trails' => 'Stopy',
    'Type' => 'Typ',
    'User' => 'Používateľ',
    'User ID' => 'ID Používateľ',
    'Yes' => 'Áno',
    'view audit entry' => 'Zobraziť položku auditu',
    '{message}' => '',
];
