#!/usr/bin/env php
<?php

require __DIR__ . '/../_init.php';
require(VENDOR_DIR . '/yiisoft/yii2/Yii.php');

Yii::setAlias('@tests', __DIR__ . '/../../..');
Yii::setAlias('@tests/app', '@tests/codeception/_app');

defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$config = require(__DIR__ . '/config/console.php');
unset($config['bootstrap']); // don't bootstrap anything here

$exitCode = (new yii\console\Application($config))->run();
exit($exitCode);
