<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action' => '',
    'Added at' => '',
    'Audit Entries' => '',
    'Audit Entry #{entry}' => '',
    'Audit Entry #{id}' => '',
    'Audit Trail #{id}' => '',
    'Difference' => '',
    'End Time' => '',
    'Entry #{i}' => '',
    'Entry ID' => '',
    'Entry Id' => '',
    'Error #{i}' => '',
    'Errors ({i})' => '',
    'Extra data ({i})' => '',
    'Field' => '',
    'Guest' => '',
    'ID' => '',
    'Javascript ({i})' => '',
    'Location' => '',
    'Max. Memory Usage' => '',
    'Memory Usage' => '',
    'New Value' => '',
    'Old Value' => '',
    'Request' => '',
    'Request Duration' => '',
    'Request method' => '',
    'Stamp' => '',
    'Start Time' => '',
    'Trail ({i})' => '',
    'Type' => '',
    'User' => '',
    'User ID' => '',
];
