<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />dans <i>{file}</i> à la ligne <i>{line}</i>.<br/>-- {link}' => '',
    'Action' => 'Action',
    'Args' => '',
    'Audit' => 'Audit',
    'Audit Error in Audit Entry #{entry_id}' => 'Erreur Audit dans Entrée Audit #{entry_id}',
    'Audit Module' => 'Module Audit',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => 'Appellé',
    'Created' => 'Créé',
    'Data' => 'Données',
    'Database Trails' => 'Pistes de Base de données',
    'Diff' => '',
    'Difference' => 'Différence',
    'Download' => 'Télécharger',
    'Download eml file' => 'Télécharger le fichier eml',
    'Duration' => 'Durée',
    'Email Messages' => 'Messages Email',
    'Emailed' => 'Mail envoyé',
    'Entries' => 'Entrées',
    'Entry #{id}' => 'Entrée #{id}',
    'Entry ID' => 'ID de l\'Entrée',
    'Error' => 'Erreur',
    'Error #{id}' => 'Erreur #{id}',
    'Error Code' => 'Code d\'Erreur',
    'Errors' => 'Erreurs',
    'Extra' => 'Supplément',
    'Extra Data' => 'Données Supplémentaires',
    'Field' => 'Champ',
    'File' => 'Fichier',
    'From' => 'De',
    'Guest' => 'Invité',
    'HTML' => '',
    'HTML Body' => 'Corps HTML',
    'Hash' => '',
    'ID' => '',
    'IP' => '',
    'Javascript' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => 'Ligne',
    'Mail' => '',
    'Mail #{id}' => '',
    'Mails' => '',
    'Memory' => 'Mémoire',
    'Message' => 'Message',
    'Model ID' => '',
    'New Value' => 'Nouvelle Valeur',
    'No' => '',
    'Old Value' => 'Ancienne Valeur',
    'Origin' => 'Origine',
    'Profiling' => 'Profilage',
    'Reply' => 'Réponse',
    'Request' => 'Requête',
    'Request Method' => 'Méthode de Requête',
    'Stack Trace' => 'Trace de la Pile',
    'Subject' => 'Sujet',
    'Successful' => 'Réussi',
    'Text' => 'Texte',
    'Text Body' => 'Corps du Texte',
    'To' => 'à',
    'Trace' => 'Trace',
    'Trail' => 'Piste',
    'Trail #{id}' => 'Piste #{id}',
    'Trails' => 'Pistes',
    'Type' => 'Type',
    'User' => 'Utilisateur',
    'User ID' => 'ID Utilisateur',
    'Yes' => 'Oui',
    'view audit entry' => 'voir l\'entrée d\'audit',
    '{message}' => '',
];
