<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '',
    'Action' => '动作',
    'Args' => '参数',
    'Audit' => '审计',
    'Audit Error in Audit Entry #{entry_id}' => '',
    'Audit Module' => '审计模块',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => '',
    'Created' => '创建时间',
    'Data' => '',
    'Database Trails' => '',
    'Diff' => '',
    'Difference' => '',
    'Download' => '下载',
    'Download eml file' => '下载eml文件',
    'Duration' => '响应时间',
    'Email Messages' => '邮件信息',
    'Emailed' => '',
    'Entries' => '访问日志',
    'Entry #{id}' => '记录 #{id}',
    'Entry ID' => '访问 ID',
    'Error' => '错误',
    'Error #{id}' => '错误 #{id}',
    'Error Code' => '错误码',
    'Errors' => '错误日志',
    'Extra' => '',
    'Extra Data' => '',
    'Field' => '字段',
    'File' => '文件',
    'From' => '发件人',
    'Guest' => '',
    'HTML' => '',
    'HTML Body' => '',
    'Hash' => '',
    'ID' => '',
    'IP' => '',
    'Javascript' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => '行号',
    'Mail' => '邮件日志',
    'Mail #{id}' => '日志 #{id}',
    'Mails' => '邮件日志',
    'Memory' => '内存',
    'Message' => '信息',
    'Model ID' => '',
    'New Value' => '新值',
    'No' => '',
    'Old Value' => '原值',
    'Origin' => '来源',
    'Profiling' => '分析',
    'Reply' => '',
    'Request' => '请求体',
    'Request Method' => '请求方法',
    'Stack Trace' => '堆栈跟踪',
    'Subject' => '主题',
    'Successful' => '',
    'Text' => '',
    'Text Body' => '',
    'To' => '收件人',
    'Trace' => '',
    'Trail' => '数据库记录',
    'Trail #{id}' => '数据库记录 #{id}',
    'Trails' => '数据库追踪',
    'Type' => '',
    'User' => '用户',
    'User ID' => '用户 ID',
    'Yes' => '',
    'view audit entry' => '查看访问记录',
    '{message}' => '',
];
