<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '',
    'Action' => '操作',
    'Args' => '參數',
    'Audit' => '稽核',
    'Audit Error in Audit Entry #{entry_id}' => '',
    'Audit Module' => '稽核模組',
    'BCC' => '',
    'CC' => '',
    'CURL' => '',
    'Called' => '',
    'Created' => '建立時間',
    'Data' => '資料',
    'Database Trails' => '資料庫紀錄',
    'Diff' => '差異',
    'Difference' => '差異',
    'Download' => '下载',
    'Download eml file' => '下载eml文件',
    'Duration' => '持續時間',
    'Email Messages' => '信件訊息',
    'Emailed' => '已發信',
    'Entries' => '訪問紀錄',
    'Entry #{id}' => '訪問紀錄 #{id}',
    'Entry ID' => '訪問 ID',
    'Error' => '錯誤紀錄',
    'Error #{id}' => '錯誤紀錄 #{id}',
    'Error Code' => '錯誤碼',
    'Errors' => '錯誤紀錄',
    'Extra' => '',
    'Extra Data' => '',
    'Field' => '欄位',
    'File' => '檔案',
    'From' => '寄件人',
    'Guest' => '訪客',
    'HTML' => '',
    'HTML Body' => '',
    'Hash' => '',
    'ID' => '',
    'IP' => '',
    'Javascript' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => '行號',
    'Mail' => '信件紀錄',
    'Mail #{id}' => '信件紀錄 #{id}',
    'Mails' => '信件紀錄',
    'Memory' => '記憶體',
    'Message' => '訊息',
    'Model ID' => '',
    'New Value' => '新值',
    'No' => '不是',
    'Old Value' => '原值',
    'Origin' => '來源',
    'Profiling' => '性能分析',
    'Reply' => '回覆',
    'Request' => '請求',
    'Request Method' => '請求方法',
    'Stack Trace' => '',
    'Subject' => '主题',
    'Successful' => '成功',
    'Text' => '',
    'Text Body' => '',
    'To' => '收件人',
    'Trace' => '',
    'Trail' => '資料庫紀錄',
    'Trail #{id}' => '資料庫紀錄 #{id}',
    'Trails' => '資料庫紀錄',
    'Type' => '類型',
    'User' => '使用者',
    'User ID' => '使用者 ID',
    'Yes' => '是',
    'view audit entry' => '查看訪問紀錄',
    '{message}' => '{message}',
];
