<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '<b>{message}</b><br /> <i>{file}</i> doyasında <i>{line}</i> satır.<br/>-- {link}',
    'Action' => 'Aksiyon',
    'Args' => 'Args',
    'Audit' => 'Denetim',
    'Audit Error in Audit Entry #{entry_id}' => 'Denetleme Kaydında Denetim Hatası #{entry_id}',
    'Audit Module' => 'Denetim Modülü',
    'BCC' => 'BCC',
    'CC' => 'CC',
    'CURL' => 'CURL',
    'Called' => 'Çağrılan',
    'Created' => 'Oluşturulan',
    'Data' => 'Veri',
    'Database Trails' => 'Veritabanı İzleri',
    'Diff' => 'Fark',
    'Difference' => 'Farklılık',
    'Download' => 'İndir',
    'Download eml file' => 'eml dosyasını indir',
    'Duration' => 'Devam Süresi',
    'Email Messages' => 'E-posta Mesajları',
    'Emailed' => 'E-posta Gönderilmiş',
    'Entries' => 'Kayıtlar',
    'Entry #{id}' => 'Kayıt #{id}',
    'Entry ID' => 'Kayıt ID',
    'Error' => 'Hata',
    'Error #{id}' => 'Hata #{id}',
    'Error Code' => 'Hata Kodu',
    'Errors' => 'Hatalar',
    'Extra' => 'Ekstra',
    'Extra Data' => 'Ekstra Veri',
    'Field' => 'Alan',
    'File' => 'Dosya',
    'From' => 'Kimden',
    'Guest' => 'Misafir',
    'HTML' => 'HTML',
    'HTML Body' => 'HTML Gövde',
    'Hash' => 'Sağlama',
    'ID' => 'ID',
    'IP' => 'IP',
    'Javascript' => 'Javascript',
    'Javascript #{id}' => 'Javascript #{id}',
    'Javascripts' => 'Javascriptler',
    'Line' => 'Satır',
    'Mail' => 'Posta',
    'Mail #{id}' => 'Posta #{id}',
    'Mails' => 'Postalar',
    'Memory' => 'Bellek',
    'Message' => 'Mesaj',
    'Model ID' => 'Model ID',
    'New Value' => 'Yeni Değer',
    'No' => 'Hayır',
    'Old Value' => 'Eski Değer',
    'Origin' => 'Başnokta',
    'Profiling' => 'Ayrımlama',
    'Reply' => 'Yanıt',
    'Request' => 'İstek',
    'Request Method' => 'İStek Metodu',
    'Stack Trace' => 'Yığın İzleme',
    'Subject' => 'Konu',
    'Successful' => 'Başarılı',
    'Text' => 'Metin',
    'Text Body' => 'Metin Gövdesi',
    'To' => 'Kime',
    'Trace' => 'İzlemek',
    'Trail' => 'İz',
    'Trail #{id}' => 'İz #{id}',
    'Trails' => 'İzler',
    'Type' => 'Tür',
    'User' => 'Kullanıcı',
    'User ID' => 'Kullanıcı ID',
    'Yes' => 'Evet',
    'view audit entry' => 'denetleme kaynını görüntüle',
    '{message}' => '{message}',
];
